name: busybox
services:
  busybox:
    command:
    - tail
    - -f
    - /dev/null
    image: bayudwiyansatria/busybox:dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: busybox
    ports: []
    volumes: 
    - ..:/workspace
    networks:
    - busybox
networks:
  busybox:
    name: busybox