name: Containerization
on:
  workflow_call:
    inputs:
      DOCKER_REGISTRY:
        type: string
        required: true
      DOCKER_USERNAME:
        type: string
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.DOCKER_REGISTRY }}
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: |
        docker build -t ${{ inputs.DOCKER_REGISTRY }}/${{ github.repository }}:latest .
        docker push ${{ inputs.DOCKER_REGISTRY }}/${{ github.repository }}:latest