name: Gradle
on:
  workflow_dispatch:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Gradle
      #-----------------------------------------------------------------------------------------------------------------
      VERSION:
        type: string
        description: "Please Refer to: https://gradle.org/releases/"
        required: true
        default: "8.4"
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Containerization
  #---------------------------------------------------------------------------------------------------------------------
  docker-latest:
    if: ${{ inputs.VERSION == '8.4' }}
    name: Docker Latest
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/gradle/Dockerfile
      DOCKER_IMAGE_TAG: gradle-${{ inputs.VERSION }}
      DOCKER_PUSH_ENABLED: true
      DOCKER_BUILD_ARG: VERSION=${{ inputs.VERSION }}
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker:
    if: ${{ inputs.VERSION != '8.4' }}
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/gradle/Dockerfile
      DOCKER_IMAGE_TAG: gradle-${{ inputs.VERSION }}
      DOCKER_PUSH_ENABLED: true
      DOCKER_BUILD_ARG: VERSION=${{ inputs.VERSION }}
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
