name: Gradle
on:
  workflow_dispatch:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Gradle
      #-----------------------------------------------------------------------------------------------------------------
      VERSION:
        type: string
        required: true
        default: '8.4'
  workflow_call:
    inputs:
      DOCKER_REGISTRY:
        type: string
        required: true
      DOCKER_USERNAME:
        type: string
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true
jobs:
  #-------------------------------------------------------------------------------------------------------------------
  # Containerization
  #-------------------------------------------------------------------------------------------------------------------
  docker-latest:
    if: ${{ github.event.inputs.VERSION }} == '8.4'
    name: Docker Latest
    uses: ./.github/workflows/docker.yaml
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ github.repository_owner }}
      MODULES: gradle
      TAG: gradle-latest
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker:
    name: Docker
    uses: ./.github/workflows/docker.yaml
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ github.repository_owner }}
      MODULES: gradle
      TAG: gradle-${{ github.event.inputs.VERSION }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}