name: JVM
on:
  workflow_dispatch:
    inputs:
      # Please Refer to: https://www.postgresql.org/support/versioning/
      VERSION:
        type: string
        required: true
        default: '11.0.17'
  workflow_call:
    inputs:
      DOCKER_REGISTRY:
        type: string
        required: true
      DOCKER_USERNAME:
        type: string
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true
jobs:
  docker:
    name: Docker
    uses: ./.github/workflows/docker.yaml
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ github.repository_owner }}
      MODULES: jvm
      TAG: java-${{ github.event.inputs.VERSION }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}