name: JVM
on:
  workflow_dispatch:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Java
      #-----------------------------------------------------------------------------------------------------------------
      VERSION:
        type: string
        description: "Java version"
        required: true
        default: "21"
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Containerization
  #---------------------------------------------------------------------------------------------------------------------
  docker-latest:
    if: ${{ inputs.VERSION == '21' }}
    name: Docker Latest
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/jvm/Dockerfile
      DOCKER_IMAGE_TAG: java-latest
      DOCKER_BUILD_ARG: VERSION=latest
      PUSH_ENABLED: true
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker:
    if: ${{ inputs.VERSION != '21' }}
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/jvm/Dockerfile
      DOCKER_IMAGE_TAG: java-${{ inputs.VERSION }}
      DOCKER_BUILD_ARG: VERSION=${{ inputs.VERSION }}
      PUSH_ENABLED: true
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
