name: Maven
on:
  workflow_dispatch:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Maven
      #-----------------------------------------------------------------------------------------------------------------
      VERSION:
        type: string
        description: "Maven Version"
        required: true
        default: "3.9.5"
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Containerization
  #---------------------------------------------------------------------------------------------------------------------
  docker-latest:
    if: ${{ inputs.VERSION == '3.9.5' }}
    name: Docker Latest
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/maven/Dockerfile
      DOCKER_IMAGE_TAG: maven-${{ inputs.VERSION }}
      DOCKER_PUSH_ENABLED: true
      DOCKER_BUILD_ARG: VERSION=${{ inputs.VERSION }}
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker:
    if: ${{ inputs.VERSION != '3.9.5' }}
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/maven/Dockerfile
      DOCKER_IMAGE_TAG: maven-${{ inputs.VERSION }}
      DOCKER_PUSH_ENABLED: true
      DOCKER_BUILD_ARG: VERSION=${{ inputs.VERSION }}
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
