name: Maven
on:
  workflow_dispatch:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Maven
      #-----------------------------------------------------------------------------------------------------------------
      VERSION:
        type: string
        required: true
        default: '3.9.5'
  workflow_call:
    inputs:
      DOCKER_REGISTRY:
        type: string
        required: true
      DOCKER_USERNAME:
        type: string
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true
jobs:
  #-------------------------------------------------------------------------------------------------------------------
  # Containerization
  #-------------------------------------------------------------------------------------------------------------------
  docker-latest:
    if: github.event.inputs.VERSION == '3.9.5'
    name: Docker Latest
    uses: ./.github/workflows/docker.yaml
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ github.repository_owner }}
      MODULES: maven
      VERSION: ${{ github.event.inputs.VERSION }}
      TAG: maven-${{ github.event.inputs.VERSION }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker:
    name: Docker
    uses: ./.github/workflows/docker.yaml
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ github.repository_owner }}
      MODULES: maven
      VERSION: ${{ github.event.inputs.VERSION }}
      TAG: maven-${{ github.event.inputs.VERSION }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}