name: MongoDB
on:
  workflow_dispatch:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # MongoDB
      #-----------------------------------------------------------------------------------------------------------------
      VERSION:
        type: string
        description: 'MongoDB Version'
        required: true
        default: '5.0'
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Containerization
  #---------------------------------------------------------------------------------------------------------------------
  docker-latest:
    if: ${{ inputs.VERSION == '5.0' }}
    name: Docker Latest
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/mongodb-client/Dockerfile
      DOCKER_IMAGE_TAG: mongodb-client-latest
      DOCKER_BUILD_ARG: VERSION=latest
      PUSH_ENABLED: true
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker:
    if: ${{ inputs.VERSION != '5.0' }}
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/mongodb-client/Dockerfile
      DOCKER_IMAGE_TAG: mongodb-client-${{ inputs.VERSION }}
      DOCKER_BUILD_ARG: VERSION=${{ inputs.VERSION }}
      PUSH_ENABLED: true
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
