name: MongoDB
on:
  workflow_dispatch:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # MongoDB
      #-----------------------------------------------------------------------------------------------------------------
      VERSION:
        type: string
        required: true
        default: '5.0'
  workflow_call:
    inputs:
      DOCKER_REGISTRY:
        type: string
        required: true
      DOCKER_USERNAME:
        type: string
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true
jobs:
  #-------------------------------------------------------------------------------------------------------------------
  # Containerization
  #-------------------------------------------------------------------------------------------------------------------
  docker-latest:
    if: ${{ github.event.inputs.VERSION }} == '5.0'
    name: Docker Latest
    uses: ./.github/workflows/docker.yaml
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ github.repository_owner }}
      MODULES: mongodb-client
      VERSION: ${{ github.event.inputs.VERSION }}
      TAG: mongodb-client-${{ github.event.inputs.VERSION }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker:
    if: ${{ github.event.inputs.VERSION }} == '5.0'
    name: Docker
    uses: ./.github/workflows/docker.yaml
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ github.repository_owner }}
      MODULES: mongodb-client
      VERSION: ${{ github.event.inputs.VERSION }}
      TAG: mongodb-client-${{ github.event.inputs.VERSION }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}