#name: PostgreSQL Client
#on:
#  push:
#    branches:
#    - master
#jobs:
#  docker:
#    name: Docker
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        java-version: [11.0.3]
#        operating-system: [ubuntu-latest]
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#    - name: Download artifacts
#      uses: actions/download-artifact@v1
#      with:
#        name: build
#        path: target/
#    - name: Login to Registry
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
#    - name: Tags
#      id: tags
#      run: |
#        echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})
#    - name: Build
#      run: |
#        docker build -t ghcr.io/bgsi-registry/satumedis-fhir-bridge-service:sha-${{ steps.tags.outputs.sha_short }} -f docker/Dockerfile-ci .
#        docker push ghcr.io/bgsi-registry/satumedis-fhir-bridge-service:sha-${{ steps.tags.outputs.sha_short }}