name: PostgreSQL
on:
  workflow_dispatch:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # PostgreSQL
      #-----------------------------------------------------------------------------------------------------------------
      # Please Refer to: https://www.postgresql.org/support/versioning/
      VERSION:
        type: string
        description: 'PostgreSQL Version'
        required: true
        default: '14'
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Containerization
  #---------------------------------------------------------------------------------------------------------------------
  docker-latest:
    if: ${{ inputs.VERSION == '14' }} 
    name: Docker Latest
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/postgresql-client/Dockerfile
      DOCKER_IMAGE_TAG: postgresql-client-${{ inputs.VERSION }}
      DOCKER_PUSH_ENABLED: true
      DOCKER_BUILD_ARG: VERSION=${{ inputs.VERSION }}
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker:
    if: ${{ inputs.VERSION != '14' }} 
    name: Build
    uses: bayudwiyansatria/.github/.github/workflows/build-docker.yml@master
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_FILE: modules/postgresql-client/Dockerfile
      DOCKER_IMAGE_TAG: postgresql-client-${{ inputs.VERSION }}
      DOCKER_PUSH_ENABLED: true
      DOCKER_BUILD_ARG: VERSION=${{ inputs.VERSION }}
      ARTIFACT_ENABLED: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
