name: PostgreSQL
on:
  workflow_dispatch:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # PostgreSQL
      #-----------------------------------------------------------------------------------------------------------------
      # Please Refer to: https://www.postgresql.org/support/versioning/
      VERSION:
        type: string
        required: true
        default: '14'
  workflow_call:
    inputs:
      DOCKER_REGISTRY:
        type: string
        required: true
      DOCKER_USERNAME:
        type: string
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true
jobs:
  #-------------------------------------------------------------------------------------------------------------------
  # Containerization
  #-------------------------------------------------------------------------------------------------------------------
  docker-latest:
    if: ${{ github.event.inputs.VERSION }} == '14'
    name: Docker Latest
    uses: ./.github/workflows/docker.yaml
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ github.repository_owner }}
      MODULES: postgresql-client
      VERSION: ${{ github.event.inputs.VERSION }}
      TAG: postgresql-client-${{ github.event.inputs.VERSION }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  docker:
    name: Docker
    uses: ./.github/workflows/docker.yaml
    with:
      DOCKER_REGISTRY: docker.io
      DOCKER_USERNAME: ${{ github.repository_owner }}
      MODULES: postgresql-client
      VERSION: ${{ github.event.inputs.VERSION }}
      TAG: postgresql-client-${{ github.event.inputs.VERSION }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}